service: serverless-jwt-auth

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-southeast-2
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

plugins:
  - serverless-offline

functions:
  verify-token:
    handler: app/Middleware/VerifyToken.auth

  login:
    handler: app/Controllers/Users.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: app/Controllers/Users.register
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: app/Controllers/Users.me
    events:
      - http:
          path: me
          method: get
          cors: true
          authorizer: verify-token

  getTasks:
    handler: app/Controllers/Tasks.list
    events:
      - http:
          path: tasks
          method: get
          cors: true
          authorizer: verify-token

  createTask:
    handler: app/Controllers/Tasks.create
    events:
      - http:
          path: task
          method: post
          cors: true
          authorizer: verify-token
